# Generated by Django 3.2.4 on 2021-11-20 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Annonces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonces',
            name='add_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
