# Generated by Django 3.2.4 on 2021-11-20 10:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cellules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('groupe', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('billan_de_la_cellule', ckeditor.fields.RichTextField()),
                ('date', models.DateField()),
                ('add_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvenementSpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_d_evenement', models.CharField(max_length=100)),
                ('emplacement', models.CharField(max_length=100)),
                ('billan_de_l_evenement', ckeditor.fields.RichTextField()),
                ('date', models.DateField()),
                ('add_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
