# Generated by Django 3.2.4 on 2021-11-16 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supports', '0002_region_reponses'),
        ('Eglises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='districts',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Supports.region'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nom_du_pasteur_du_groupe', models.CharField(max_length=200)),
                ('nombre_de_districts', models.IntegerField()),
                ('emplacement', models.CharField(max_length=300)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supports.region')),
            ],
        ),
    ]
