# Generated by Django 3.2.4 on 2021-11-16 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Eglises', '0002_auto_20211116_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='districts',
            name='groupe',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
