# Generated by Django 3.2.4 on 2021-11-19 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Eglises', '0004_auto_20211118_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='add_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jeunesdifficultes',
            name='groupe_du_concerne',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jeunesdifficultes',
            name='region_du_concerne',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='groupe_du_concerne',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='region_du_concerne',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='districts',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='groups',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
