# Generated by Django 3.2.4 on 2021-11-16 16:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Eglises', '0002_auto_20211116_1601'),
        ('Supports', '0002_region_reponses'),
        ('JeunesApps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeunespost',
            name='groupe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Eglises.groups'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jeunespost',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Supports.region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ouviresjeunespost',
            name='groupe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Eglises.groups'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ouviresjeunespost',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Supports.region'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jeunespost',
            name='les_freres_sont_ils_dans_leglise',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jeunespost',
            name='les_parents_sont_ils_dans_leglise',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jeunespost',
            name='les_soeurs_sont_elles_dans_leglise',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jeunespost',
            name='talents_du_jeune',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='ouviresjeunespost',
            name='les_freres_sont_ils_dans_leglise',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ouviresjeunespost',
            name='les_parents_sont_ils_dans_leglise',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ouviresjeunespost',
            name='les_soeurs_sont_elles_dans_leglise',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ouviresjeunespost',
            name='talents_de_l_ouvrier',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
