# Generated by Django 3.2.4 on 2021-11-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JeunesApps', '0002_auto_20211116_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeunespost',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jeunespost',
            name='groupe',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jeunespost',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jeunespost',
            name='sexe',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ouviresjeunespost',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ouviresjeunespost',
            name='groupe',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ouviresjeunespost',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ouviresjeunespost',
            name='sexe',
            field=models.CharField(max_length=100),
        ),
    ]
