# Generated by Django 3.2.4 on 2021-11-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JeunesApps', '0003_auto_20211117_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeunespost',
            name='distance_maison_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jeunespost',
            name='distance_maison_ecole',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ouviresjeunespost',
            name='distance_maison_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ouviresjeunespost',
            name='distance_maison_lieu_de_travail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
