# Generated by Django 3.2.4 on 2021-11-30 09:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Supports', '0002_region_reponses'),
        ('Adultes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultespost',
            name='groupe_sanguin',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adultespost',
            name='rhesus',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adultespost',
            name='role_dans_leglise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Supports.roles'),
            preserve_default=False,
        ),
    ]
