# Generated by Django 3.2.4 on 2021-11-30 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Adultes', '0002_auto_20211130_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultespost',
            name='dirigeant',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
